"""Generate spreadsheet reference pages from the extraction bindings."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
BINDINGS = ROOT / "tests" / "bindings"
USER_GUIDE = ROOT / "user_guide"


def _load(name: str) -> list[dict[str, Any]]:
    document = yaml.safe_load((BINDINGS / name).read_text(encoding="utf-8"))
    return document["series"]


def _escape(value: object) -> str:
    text = str(value).replace("\n", " ").replace("|", r"\|")
    return " ".join(text.split())


def _label(identifier: str) -> str:
    return identifier.replace("_", " ").replace(".", " — ").strip().title()


def _ranges(series: dict[str, Any]) -> str:
    ranges = series.get("data_range", "")
    if not isinstance(ranges, list):
        ranges = [ranges]
    return "<br>".join(f"`{_escape(item)}`" for item in ranges if item)


def _dimensions(series: dict[str, Any]) -> str:
    dimensions = series.get("structure", {}).get("dimensions", [])
    names = [item.get("concept") or item.get("id") for item in dimensions]
    return ", ".join(f"`{_escape(name)}`" for name in names if name) or "—"


def _domain(series: dict[str, Any]) -> str:
    domain = series.get("input", {}).get("domain", {})
    if not domain:
        return "Workbook-defined"
    if "enum" in domain:
        values = domain["enum"]
        if len(values) <= 8:
            return ", ".join(f"`{_escape(value)}`" for value in values)
        sample = ", ".join(f"`{_escape(value)}`" for value in values[:5])
        return f"{sample}, … ({len(values)} allowed values)"
    for key in ("between", "real_between"):
        if key in domain:
            bounds = domain[key]
            return f"{_escape(bounds['min'])} to {_escape(bounds['max'])}"
    return _escape(domain)


def _dtype(series: dict[str, Any]) -> str:
    return _escape(
        series.get("structure", {}).get("measure", {}).get("dtype", "value")
    )


def _write(path: Path, content: str, *, check: bool) -> bool:
    content = content.rstrip() + "\n"
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return False
    if check:
        raise SystemExit(f"{path.relative_to(ROOT)} is out of date")
    path.write_text(content, encoding="utf-8")
    return True


def render_inputs(series: list[dict[str, Any]]) -> str:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in series:
        grouped[item["sheet"]].append(item)

    lines = [
        "---",
        'title: "Spreadsheet inputs"',
        'guide-section: "Spreadsheet Guide"',
        "---",
        "",
        "<!-- Generated by docs-source/generate_spreadsheet_guide.py. -->",
        "",
        "This reference is generated from `tests/bindings/inputs.bindings.yaml`.",
        "It lists the workbook cells that feed the published LIC-DSF calculations.",
        "Use the spreadsheet's yellow input cells and built-in instructions as the",
        "primary workflow; entries on calculation sheets are advanced controls.",
        "",
        "Values must use the workbook's units, signs, labels, and year ordering.",
        "A range represents a named series, not a set of interchangeable cells.",
        "",
    ]

    for sheet, items in grouped.items():
        lines.extend(
            [
                f"## {_escape(sheet)}",
                "",
                "| Input | Cell or range | Type | Dimensions | Allowed values | Purpose |",
                "|---|---|---|---|---|---|",
            ]
        )
        for item in items:
            lines.append(
                "| {name} | {ranges} | `{dtype}` ({layout}) | {dimensions} | "
                "{domain} | {notes} |".format(
                    name=_escape(_label(item["id"])),
                    ranges=_ranges(item),
                    dtype=_dtype(item),
                    layout=_escape(item.get("layout", "scalar")),
                    dimensions=_dimensions(item),
                    domain=_domain(item),
                    notes=_escape(item.get("notes", "—")),
                )
            )
        lines.append("")

    lines.extend(
        [
            "## Scope",
            "",
            "This is the public input surface of the extracted calculation graph. It",
            "does not replace the workbook's own validation messages, comments, or",
            "economic guidance, and it does not imply that every listed advanced",
            "control should be edited for a normal country DSA.",
        ]
    )
    return "\n".join(lines)


def render_outputs(series: list[dict[str, Any]]) -> str:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in series:
        table = item.get("series_context", {}).get("TABLE", item["sheet"])
        grouped[table].append(item)

    lines = [
        "---",
        'title: "Spreadsheet outputs"',
        'guide-section: "Spreadsheet Guide"',
        "---",
        "",
        "<!-- Generated by docs-source/generate_spreadsheet_guide.py. -->",
        "",
        "This reference is generated from `tests/bindings/outputs.bindings.yaml`.",
        "It covers the published `Chart Data` calculation surface: mechanical risk",
        "signals and the scenario paths behind the standard debt-stress figures.",
        "",
        "A scalar returns one value. A series returns values identified by its named",
        "dimensions, commonly scenario and projection year. A breach or applicability",
        "flag uses `0` for no and `1` for yes.",
        "",
    ]

    for table, items in grouped.items():
        lines.extend(
            [
                f"## {_label(table)}",
                "",
                "| Output | Cell or range | Type | Dimensions | Meaning |",
                "|---|---|---|---|---|",
            ]
        )
        for item in items:
            lines.append(
                "| {name} | {ranges} | `{dtype}` ({layout}) | {dimensions} | "
                "{notes} |".format(
                    name=_escape(_label(item["id"])),
                    ranges=_ranges(item),
                    dtype=_dtype(item),
                    layout=_escape(item.get("layout", "scalar")),
                    dimensions=_dimensions(item),
                    notes=_escape(item.get("notes", "—")),
                )
            )
        lines.append("")

    lines.extend(
        [
            "## Scope",
            "",
            "These bindings describe selected `Chart Data` results, not every formatted",
            "cell on Outputs 1–7. Realism diagnostics, the probability approach,",
            "narrative judgement, chart formatting, and workbook macros remain separate",
            "spreadsheet surfaces.",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if committed guide pages differ from the bindings.",
    )
    args = parser.parse_args()

    changed = [
        _write(
            USER_GUIDE / "09-spreadsheet-inputs.qmd",
            render_inputs(_load("inputs.bindings.yaml")),
            check=args.check,
        ),
        _write(
            USER_GUIDE / "10-spreadsheet-outputs.qmd",
            render_outputs(_load("outputs.bindings.yaml")),
            check=args.check,
        ),
    ]
    if any(changed):
        print("Updated spreadsheet input/output guide pages.")
    elif not args.check:
        print("Spreadsheet guide pages are already current.")


if __name__ == "__main__":
    main()
